/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.projeto_integrador.view;

import com.mycompany.projeto_integrador.model.Usuario;


public class TelaMenu extends javax.swing.JFrame {

    private final Usuario usuario;

    /**
     * Creates new form TelaMenu
     * @param usuario
     */
    public TelaMenu(Usuario usuario) {
        this.usuario = usuario;
        initComponents();
        setTitle("Menu Principal");
        aplicarPermissoes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        botaoCadastro = new javax.swing.JButton();
        botaoConsulta = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Menu");

        botaoCadastro.setBackground(new java.awt.Color(51, 153, 255));
        botaoCadastro.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        botaoCadastro.setText("Cadastro");
        botaoCadastro.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        botaoCadastro.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        botaoCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCadastroActionPerformed(evt);
            }
        });

        botaoConsulta.setBackground(new java.awt.Color(51, 153, 255));
        botaoConsulta.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        botaoConsulta.setText("Consulta");
        botaoConsulta.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        botaoConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoConsultaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(172, 172, 172)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(botaoCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(86, 86, 86)
                        .addComponent(botaoConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(96, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(166, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCadastroActionPerformed
        // TODO add your handling code here:
        new TelaCadastro(usuario).setVisible(true); //Abre a tela de cadastro
    }//GEN-LAST:event_botaoCadastroActionPerformed

    private void botaoConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoConsultaActionPerformed
        // TODO add your handling code here:
        new TelaConsulta(usuario).setVisible(true);// Abre a tela de consulta
    }//GEN-LAST:event_botaoConsultaActionPerformed

    private void aplicarPermissoes() {
    if (usuario == null) {
        System.out.println("[ERRO] Usuario nulo ao aplicar permissoes");
        return;
    }

    String tipo = usuario.getTipoUsuario();
    if (tipo == null) tipo = "";
    tipo = tipo.trim().toLowerCase();

    System.out.println("\n=== APLICANDO PERMISSOES ===");
    System.out.println("Usuario: " + usuario.getNome());
    System.out.println("Tipo (normalizado): " + tipo);
    System.out.println("botaoCadastro.isEnabled() antes = " + botaoCadastro.isEnabled());
    System.out.println("botaoConsulta.isEnabled() antes = " + botaoConsulta.isEnabled());

    switch (tipo) {
        case "administrador" -> {
            System.out.println("Permissão ADMIN: todos os botões habilitados");
            botaoCadastro.setEnabled(true);
            botaoConsulta.setEnabled(true);
        }
        case "operador" -> {
            System.out.println("Permissão OPERADOR: pode consultar, mas não cadastrar");
            botaoCadastro.setEnabled(true);
            botaoConsulta.setEnabled(true);
        }
        case "usuario" -> {
            System.out.println("Permissão USUARIO: apenas consultar");
            botaoCadastro.setEnabled(false);
            botaoConsulta.setEnabled(true);
        }
        default -> {
            System.out.println("[ERRO] Tipo de usuário inválido: " + tipo);
        }
    }

    System.out.println("botaoCadastro.isEnabled() depois = " + botaoCadastro.isEnabled());
    System.out.println("botaoConsulta.isEnabled() depois = " + botaoConsulta.isEnabled());
    System.out.println("============================\n");
}

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoCadastro;
    private javax.swing.JButton botaoConsulta;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
